scheduler/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^', include('schedulingcalendar.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

schedulingcalendar/urls.py
from django.conf.urls import url

from views import *

app_name = 'schedulingcalendar'
urlpatterns = [
    url(r'^$', front_or_cal_page, name='front_or_cal_page'),
    url(r'^front/$', front_page, name='front_page'),
    url(r'^about/$', about_page, name='about_page'),
    url(r'^help/$', help_page, name='help_page'),
    url(r'^contact/$', contact_page, name='contact_page'),
    url(r'^login_success/$', login_success, name='login_success'),
    url(r'^account_settings/$', account_settings, name='account_settings'),
    url(r'^password/$', change_password, name='change_password'),
    url(r'^register/$', register, name='register'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    url(r'^account_activation_success/$', account_activation_success, name='account_activation_success'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    url(r'^setup_new_account/$', new_manager_user_setup, name='new_manager_user_setup'),
    url(r'^forgot_username/$', forgot_username, name='forgot_username'),
    url(r'^delete_account/$', delete_account, name='delete_account'),
    url(r'^account_delete_sent/$', account_delete_sent, name='account_delete_sent'),
    url(r'^delete_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', delete_confirm, name='delete_confirm'),
    url(r'^account_delete_feedback_send/$', account_delete_feedback_send, name='account_delete_feedback_send'),
    url(r'^change_email/$', change_email, name='change_email'),
    url(r'^email_change_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/(?P<new_email>[^@]+@[^@]+\.[^@]+)/$', email_change_confirm, name='email_change_confirm'),
    url(r'^account_email_change_sent/$', account_email_change_sent, name='account_email_change_sent'),
    url(r'^check_pending_approvals/$', check_pending_approvals, name='check_pending_approvals'),
    url(r'^calendar/$', calendar_page, name='calendar_page'),
    url(r'^calendar/add_schedule$', add_schedule, name='add_schedule'),
    url(r'^calendar/get_schedules$', get_schedules, name='get_schedules'),
    url(r'^calendar/get_schedule_info$', get_schedule_info, name='get_schedule_info'),
    url(r'^calendar/get_proto_schedule_info$', get_proto_schedule_info, name='get_proto_schedule_info'),
    url(r'^calendar/add_employee_to_schedule$', add_employee_to_schedule, name='add_employee_to_schedule'),
    url(r'^calendar/remove_schedule$', remove_schedule, name='remove_schedule'),
    url(r'^calendar/edit_schedule$', edit_schedule, name='edit_schedule'),
    url(r'^calendar/copy_schedules$', copy_schedules, name='copy_schedules'),
    url(r'^calendar/remove_conflict_copy_schedules$', remove_conflict_copy_schedules, name='remove_conflict_copy_schedules'),
    url(r'^calendar/push_changes_live$', push_changes_live, name='push_changes_live'),
    url(r'^calendar/update_view_rights$', update_view_rights, name='update_view_rights'),
    url(r'^calendar/view_live_schedules$', view_live_schedules, name='view_live_schedules'),
    url(r'^calendar/get_live_schedules$', get_live_schedules, name='get_live_schedules'),
    url(r'^calendar/employee_get_live_schedules$', employee_get_live_schedules, name='employee_get_live_schedules'),
    url(r'^calendar/add_edit_day_note_header$', add_edit_day_note_header, name='add_edit_day_note_header'),
    url(r'^calendar/add_edit_day_note_body$', add_edit_day_note_body, name='add_edit_day_note_body'),
    url(r'^calendar/edit_schedule_note$', edit_schedule_note, name='edit_schedule_note'),
    url(r'^employees/$', EmployeeListView.as_view(), name='employee_list'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/info/$', EmployeeUpdateView.as_view(), name='employee_info'),
    url(r'^employees/employee_create$', EmployeeCreateView.as_view(), name='employee_create'),
    url(r'^employees/(?P<pk>[0-9]+)/employee_delete$', EmployeeDeleteView.as_view(), name='employee_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/employee_user_pw/(?P<employee_user_pk>[0-9]+)$', change_employee_pw_as_manager, name='employee_user_pw_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/employee_username/(?P<employee_user_pk>[0-9]+)$', EmployeeUsernameUpdateView.as_view(), name='employee_username_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/employee_user_delete/(?P<pk>[0-9]+)$', EmployeeUserDeleteView.as_view(), name='employee_user_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/employee_user_create$', EmployeeUserCreateView.as_view(), name='employee_user_create'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/vacation/(?P<vacation_pk>[0-9]+)$', VacationUpdateView.as_view(), name='vacation_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/vacation_delete/(?P<pk>[0-9]+)$', VacationDeleteView.as_view(), name='vacation_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/vacation_create$', VacationCreateView.as_view(), name='vacation_create'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/absent/(?P<absent_pk>[0-9]+)$', AbsentUpdateView.as_view(), name='absent_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/absent_delete/(?P<pk>[0-9]+)$', AbsentDeleteView.as_view(), name='absent_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/absent_create$', AbsentCreateView.as_view(), name='absent_create'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/repeat_unavailable/(?P<repeat_unav_pk>[0-9]+)$', RepeatUnavailableUpdateView.as_view(), name='repeat_unav_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/repeat_unavailable_delete/(?P<pk>[0-9]+)$', RepeatUnavailableDeleteView.as_view(), name='repeat_unav_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/repeat_unavailable_create$', RepeatUnavailableCreateView.as_view(), name='repeat_unav_create'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/desired_time/(?P<desired_time_pk>[0-9]+)$', DesiredTimeUpdateView.as_view(), name='desired_time_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/desired_time_delete/(?P<pk>[0-9]+)$', DesiredTimeDeleteView.as_view(), name='desired_time_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/desired_time_create$', DesiredTimeCreateView.as_view(), name='desired_time_create'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/department_membership/(?P<dep_mem_pk>[0-9]+)$', DepartmentMembershipUpdateView.as_view(), name='dep_mem_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/department_membership_delete/(?P<pk>[0-9]+)$', DepartmentMembershipDeleteView.as_view(), name='dep_mem_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/department_membership_create$', DepartmentMembershipCreateView.as_view(), name='dep_mem_create'),
    url(r'^employees/employee_vacation_application_create$', EmployeeVacationApplicationCreateView.as_view(), name='employee_vacation_application_create'),
    url(r'^employees/employee_vacation_application_delete/(?P<pk>[0-9]+)$', EmployeeVacationApplicationDeleteView.as_view(), name='employee_vacation_application_delete'),
    url(r'^employees/employee_absence_application_create$', EmployeeAbsenceApplicationCreateView.as_view(), name='employee_absence_application_create'),
    url(r'^employees/employee_absence_application_delete/(?P<pk>[0-9]+)$', EmployeeAbsenceApplicationDeleteView.as_view(), name='employee_absence_application_delete'),
    url(r'^employees/employee_repeat_unavailability_application_create$', EmployeeRepeatUnavailabilityApplicationCreateView.as_view(), name='employee_repeat_unavailability_application_create'),
    url(r'^employees/employee_repeat_unavailability_application_delete/(?P<pk>[0-9]+)$', EmployeeRepeatUnavailabilityApplicationDeleteView.as_view(), name='employee_repeat_unavailability_application_delete'),
    url(r'^employees/employee_desired_time_create$', EmployeeDesiredTimeCreateView.as_view(), name='employee_desired_time_create'),
    url(r'^employees/employee_desired_time_delete/(?P<pk>[0-9]+)$', EmployeeDesiredTimeDeleteView.as_view(), name='employee_desired_time_delete'),
    url(r'^departments/$', DepartmentListView.as_view(), name='department_list'),
    url(r'^departments/department_create$', DepartmentCreateView.as_view(), name='department_create'),
    url(r'^departments/(?P<department_pk>[0-9]+)/department_update$', DepartmentUpdateView.as_view(), name='department_update'),
    url(r'^departments/(?P<pk>[0-9]+)/department_delete$', DepartmentDeleteView.as_view(), name='department_delete'),
    url(r'^monthly_revenue/$', MonthlyRevenueListView.as_view(), name='monthly_revenue_list'),
    url(r'^monthly_revenue/monthly_revenue_create$', MonthlyRevenueCreateView.as_view(), name='monthly_revenue_create'),
    url(r'^monthly_revenue/(?P<monthly_rev_pk>[0-9]+)/monthly_revenue_update$', MonthlyRevenueUpdateView.as_view(), name='monthly_revenue_update'),
    url(r'^monthly_revenue/(?P<pk>[0-9]+)/monthly_revenue_delete$', MonthlyRevenueDeleteView.as_view(), name='monthly_revenue_delete'),
    url(r'^business_settings$', BusinessDataUpdateView.as_view(), name='business_update'),
    url(r'^calendar_display_settings$', CalendarDisplayUpdateView.as_view(), name='calendar_display_settings'),
    url(r'^live_calendar/$', employee_calendar_page, name='employee_calendar_page'),
    url(r'^live_calendar/create_schedule_swap_petition$', create_schedule_swap_petition, name='create_schedule_swap_petition'),
    url(r'^pending_approvals/$', pending_approvals_page, name='pending_approvals'),
    url(r'^pending_approvals/approve_vacation_app$', approve_vacation_app, name='approve_vacation_app'),
    url(r'^pending_approvals/disapprove_vacation_app$', disapprove_vacation_app, name='disapprove_vacation_app'),
    url(r'^pending_approvals/approve_absence_app$', approve_absence_app, name='approve_absence_app'),
    url(r'^pending_approvals/disapprove_absence_app$', disapprove_absence_app, name='disapprove_absence_app'),

templates/site/__base.html
{% load static %}
{% load schedule_calendar_extras %}
<!DOCTYPE html>

<html>
  <head>
    {% block meta_tags %}
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta_tags %}
    
    <title>
      {% block title %}ScheduleHours{% endblock title %}
    </title>
    
    {% block stylesheets %}
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css" />
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'site/css/base.css' %}" />
      <link rel="stylesheet" href="{% static 'site/css/navigation.css' %}" />
      <link rel="stylesheet" href="{% static 'site/css/bootstrap-custom.css' %}" />
      <link href="https://fonts.googleapis.com/css?family=Nanum+Myeongjo" rel="stylesheet"> 
      <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet"> 
      <link rel="shortcut icon" type="image/png" href="/static/site/images/favicon.ico" />
    {% endblock stylesheets %}
    
    {% block extra_head %}{% endblock extra_head %}
  </head>
  <body>
    <!-- Messages -->
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible fade show mb-0" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    {% endfor %}
  
    <!-- Header and navigation -->
    <header class="no-print">
      {% include "site/_navigation.html" %}
    </header>
    
    <!-- Main content -->
    <main>
      {% block content %}
      {% endblock content %}
    </main>  
    
    {% block javascript %}
      <script src="{% static 'site/js/jquery.min.js' %}" ></script>
      <script src="{% static 'site/js/moment.min.js' %}" ></script>
      <script src="{% static 'site/js/jquery.form.min.js' %}" ></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
      {% if request.user.is_authenticated %}
        {% if request.user|has_group:"Managers" %}
            <script src="{% static 'site/js/pending-approvals-nav.js' %}" ></script>
        {% endif %}
      {% endif %}
      <script>
      $(document).ready(function() {  
        $.ajaxSetup({
          data: {csrfmiddlewaretoken: "{{ csrf_token }}" },
        });
      });
      </script>
    {% endblock javascript %}
  </body>
</html>

templates/site/_navigation.html
{% load schedule_calendar_extras %}

<nav class="navbar navbar-expand-lg navbar-dark pt-0 pb-0">
  <a class="navigation-font nav-front-link" href="{% url 'schedulingcalendar:front_page' %}">ScheduleHours.com</a>
  <button id="nav-bar-collapsed-btn" class="navbar-toggler custom-nav-hamburger" type="button" data-toggle="collapse" data-target="#scheduleHoursNavbar" aria-controls="scheduleHoursNavbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="scheduleHoursNavbar">
    <ul id="header-nav" class="navbar-nav">
      {% if request.user.is_authenticated %}
        {% if request.user|has_group:"Managers" %}
        <li class="nav-item custom-nav-dropdown mr-2">
          <div class="btn-group">
            <a class="nav-link active btn btn-primary custom-nav-btn" href="{% url 'schedulingcalendar:calendar_page' %}">Calendar<span class="sr-only">(current)</span></a>
            <button type="button" class="btn btn-primary active dropdown-toggle dropdown-toggle-split custom-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'schedulingcalendar:export_to_csv_page' %}">Export To CSV</a>
              <a class="dropdown-item" href="{% url 'schedulingcalendar:calendar_display_settings' %}">Display Settings</a>
            </div>
          </div>
        </li>
        <li class="nav-item custom-nav-dropdown mr-2">
          <div class="btn-group">
            <a class="nav-link active btn custom-nav-btn" href="{% url 'schedulingcalendar:employee_list' %}">Employees<span class="sr-only">(current)</span></a>
            <button type="button" class="btn btn-primary active dropdown-toggle dropdown-toggle-split custom-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'schedulingcalendar:department_list' %}">Departments</a>
              <a class="dropdown-item" href="{% url 'schedulingcalendar:monthly_revenue_list' %}">Monthly Revenue</a>
              <a class="dropdown-item" href="{% url 'schedulingcalendar:business_update' %}">Business Settings</a>
            </div>
          </div>
        </li>
        <li class="nav-item custom-nav-item active">
          <a class="nav-link" href="{% url 'schedulingcalendar:help_page' %}">Help</a>
        </li>
        <!-- TODO: Add schedule swaps: <li id="pending-approvals-btn"><a href="{% url 'schedulingcalendar:pending_approvals' %}">Pending Approvals</a></li> -->
        {% else %}
        <li class="nav-item custom-nav-item active">
          <a class="nav-link" href="{% url 'schedulingcalendar:employee_calendar_page' %}">Schedules</a>
        </li>
        <li class="nav-item custom-nav-item active">
          <a class="nav-link" href="{% url 'schedulingcalendar:employee_availability' %}">My Availability</a>
        </li>
        <li class="nav-item custom-nav-item active">
          <a class="nav-link" href="{% url 'schedulingcalendar:employee_profile_settings' %}">Display Settings</a>
        </li>
        {% endif %}
      {% else %}
        <li class="nav-item custom-nav-item active">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item custom-nav-item active">
          <a class="nav-link" href="{% url 'schedulingcalendar:register' %}">Register</a>
        </li>
      {% endif %}
      <li class="nav-item custom-nav-item active">
        <a class="nav-link" href="{% url 'schedulingcalendar:about_page' %}">About</a>
      </li>
      <li class="nav-item custom-nav-item active">
        <a class="nav-link" href="{% url 'schedulingcalendar:contact_page' %}">Contact</a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item active">
          {% if request.user|has_group:"Managers" %}
            <div class="dropdown">
              <button class="btn btn-primary custom-nav-btn-dropdown custom-nav-item border-0 dropdown-toggle" type="button" id="accountDropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
              </button>
              <div class="dropdown-menu" aria-labelledby="accountDropdownMenuButton">
                <a class="dropdown-item nav-link" href="{% url 'schedulingcalendar:account_settings' %}">Account Settings</a>
                <a class="dropdown-item nav-link" href="{% url 'logout' %}?next={% url 'login' %}">Logout</a>
              </div>
            </div>
          {% else %}
            <a class="nav-link custom-nav-item" href="{% url 'logout' %}?next={% url 'login' %}">Logout</a>
          {% endif %}
        </li>
      {% endif %}
    </ul>
  </div>
</nav>