scheduler/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^', include('schedulingcalendar.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

schedulingcalendar/urls.py
from django.conf.urls import url

from views import *

app_name = 'schedulingcalendar'
urlpatterns = [
    url(r'^$', front_or_cal_page, name='front_or_cal_page'),
    url(r'^front/$', front_page, name='front_page'),
    url(r'^about/$', about_page, name='about_page'),
    url(r'^help/$', help_page, name='help_page'),
    url(r'^contact/$', contact_page, name='contact_page'),
    url(r'^login_success/$', login_success, name='login_success'),
    url(r'^account_settings/$', account_settings, name='account_settings'),
    url(r'^password/$', change_password, name='change_password'),
    url(r'^register/$', register, name='register'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    url(r'^account_activation_success/$', account_activation_success, name='account_activation_success'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    url(r'^setup_new_account/$', new_manager_user_setup, name='new_manager_user_setup'),
    url(r'^forgot_username/$', forgot_username, name='forgot_username'),
    url(r'^delete_account/$', delete_account, name='delete_account'),
    url(r'^account_delete_sent/$', account_delete_sent, name='account_delete_sent'),
    url(r'^delete_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', delete_confirm, name='delete_confirm'),
    url(r'^account_delete_feedback_send/$', account_delete_feedback_send, name='account_delete_feedback_send'),
    url(r'^change_email/$', change_email, name='change_email'),
    url(r'^email_change_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/(?P<new_email>[^@]+@[^@]+\.[^@]+)/$', email_change_confirm, name='email_change_confirm'),
    url(r'^account_email_change_sent/$', account_email_change_sent, name='account_email_change_sent'),
    url(r'^check_pending_approvals/$', check_pending_approvals, name='check_pending_approvals'),
    url(r'^calendar/$', calendar_page, name='calendar_page'),
    url(r'^calendar/add_schedule$', add_schedule, name='add_schedule'),
    url(r'^calendar/get_schedules$', get_schedules, name='get_schedules'),
    url(r'^calendar/get_schedule_info$', get_schedule_info, name='get_schedule_info'),
    url(r'^calendar/get_proto_schedule_info$', get_proto_schedule_info, name='get_proto_schedule_info'),
    url(r'^calendar/add_employee_to_schedule$', add_employee_to_schedule, name='add_employee_to_schedule'),
    url(r'^calendar/remove_schedule$', remove_schedule, name='remove_schedule'),
    url(r'^calendar/edit_schedule$', edit_schedule, name='edit_schedule'),
    url(r'^calendar/copy_schedules$', copy_schedules, name='copy_schedules'),
    url(r'^calendar/remove_conflict_copy_schedules$', remove_conflict_copy_schedules, name='remove_conflict_copy_schedules'),
    url(r'^calendar/push_changes_live$', push_changes_live, name='push_changes_live'),
    url(r'^calendar/update_view_rights$', update_view_rights, name='update_view_rights'),
    url(r'^calendar/view_live_schedules$', view_live_schedules, name='view_live_schedules'),
    url(r'^calendar/get_live_schedules$', get_live_schedules, name='get_live_schedules'),
    url(r'^calendar/employee_get_live_schedules$', employee_get_live_schedules, name='employee_get_live_schedules'),
    url(r'^calendar/add_edit_day_note_header$', add_edit_day_note_header, name='add_edit_day_note_header'),
    url(r'^calendar/add_edit_day_note_body$', add_edit_day_note_body, name='add_edit_day_note_body'),
    url(r'^calendar/edit_schedule_note$', edit_schedule_note, name='edit_schedule_note'),
    url(r'^employees/$', EmployeeListView.as_view(), name='employee_list'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/info/$', EmployeeUpdateView.as_view(), name='employee_info'),
    url(r'^employees/employee_create$', EmployeeCreateView.as_view(), name='employee_create'),
    url(r'^employees/(?P<pk>[0-9]+)/employee_delete$', EmployeeDeleteView.as_view(), name='employee_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/employee_user_pw/(?P<employee_user_pk>[0-9]+)$', change_employee_pw_as_manager, name='employee_user_pw_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/employee_username/(?P<employee_user_pk>[0-9]+)$', EmployeeUsernameUpdateView.as_view(), name='employee_username_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/employee_user_delete/(?P<pk>[0-9]+)$', EmployeeUserDeleteView.as_view(), name='employee_user_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/employee_user_create$', EmployeeUserCreateView.as_view(), name='employee_user_create'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/vacation/(?P<vacation_pk>[0-9]+)$', VacationUpdateView.as_view(), name='vacation_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/vacation_delete/(?P<pk>[0-9]+)$', VacationDeleteView.as_view(), name='vacation_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/vacation_create$', VacationCreateView.as_view(), name='vacation_create'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/absent/(?P<absent_pk>[0-9]+)$', AbsentUpdateView.as_view(), name='absent_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/absent_delete/(?P<pk>[0-9]+)$', AbsentDeleteView.as_view(), name='absent_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/absent_create$', AbsentCreateView.as_view(), name='absent_create'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/repeat_unavailable/(?P<repeat_unav_pk>[0-9]+)$', RepeatUnavailableUpdateView.as_view(), name='repeat_unav_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/repeat_unavailable_delete/(?P<pk>[0-9]+)$', RepeatUnavailableDeleteView.as_view(), name='repeat_unav_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/repeat_unavailable_create$', RepeatUnavailableCreateView.as_view(), name='repeat_unav_create'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/desired_time/(?P<desired_time_pk>[0-9]+)$', DesiredTimeUpdateView.as_view(), name='desired_time_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/desired_time_delete/(?P<pk>[0-9]+)$', DesiredTimeDeleteView.as_view(), name='desired_time_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/desired_time_create$', DesiredTimeCreateView.as_view(), name='desired_time_create'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/department_membership/(?P<dep_mem_pk>[0-9]+)$', DepartmentMembershipUpdateView.as_view(), name='dep_mem_update'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/department_membership_delete/(?P<pk>[0-9]+)$', DepartmentMembershipDeleteView.as_view(), name='dep_mem_delete'),
    url(r'^employees/(?P<employee_pk>[0-9]+)/department_membership_create$', DepartmentMembershipCreateView.as_view(), name='dep_mem_create'),
    url(r'^employees/employee_vacation_application_create$', EmployeeVacationApplicationCreateView.as_view(), name='employee_vacation_application_create'),
    url(r'^employees/employee_vacation_application_delete/(?P<pk>[0-9]+)$', EmployeeVacationApplicationDeleteView.as_view(), name='employee_vacation_application_delete'),
    url(r'^employees/employee_absence_application_create$', EmployeeAbsenceApplicationCreateView.as_view(), name='employee_absence_application_create'),
    url(r'^employees/employee_absence_application_delete/(?P<pk>[0-9]+)$', EmployeeAbsenceApplicationDeleteView.as_view(), name='employee_absence_application_delete'),
    url(r'^employees/employee_repeat_unavailability_application_create$', EmployeeRepeatUnavailabilityApplicationCreateView.as_view(), name='employee_repeat_unavailability_application_create'),
    url(r'^employees/employee_repeat_unavailability_application_delete/(?P<pk>[0-9]+)$', EmployeeRepeatUnavailabilityApplicationDeleteView.as_view(), name='employee_repeat_unavailability_application_delete'),
    url(r'^employees/employee_desired_time_create$', EmployeeDesiredTimeCreateView.as_view(), name='employee_desired_time_create'),
    url(r'^employees/employee_desired_time_delete/(?P<pk>[0-9]+)$', EmployeeDesiredTimeDeleteView.as_view(), name='employee_desired_time_delete'),
    url(r'^departments/$', DepartmentListView.as_view(), name='department_list'),
    url(r'^departments/department_create$', DepartmentCreateView.as_view(), name='department_create'),
    url(r'^departments/(?P<department_pk>[0-9]+)/department_update$', DepartmentUpdateView.as_view(), name='department_update'),
    url(r'^departments/(?P<pk>[0-9]+)/department_delete$', DepartmentDeleteView.as_view(), name='department_delete'),
    url(r'^monthly_revenue/$', MonthlyRevenueListView.as_view(), name='monthly_revenue_list'),
    url(r'^monthly_revenue/monthly_revenue_create$', MonthlyRevenueCreateView.as_view(), name='monthly_revenue_create'),
    url(r'^monthly_revenue/(?P<monthly_rev_pk>[0-9]+)/monthly_revenue_update$', MonthlyRevenueUpdateView.as_view(), name='monthly_revenue_update'),
    url(r'^monthly_revenue/(?P<pk>[0-9]+)/monthly_revenue_delete$', MonthlyRevenueDeleteView.as_view(), name='monthly_revenue_delete'),
    url(r'^business_settings$', BusinessDataUpdateView.as_view(), name='business_update'),
    url(r'^calendar_display_settings$', CalendarDisplayUpdateView.as_view(), name='calendar_display_settings'),
    url(r'^live_calendar/$', employee_calendar_page, name='employee_calendar_page'),
    url(r'^live_calendar/create_schedule_swap_petition$', create_schedule_swap_petition, name='create_schedule_swap_petition'),
    url(r'^pending_approvals/$', pending_approvals_page, name='pending_approvals'),
    url(r'^pending_approvals/approve_vacation_app$', approve_vacation_app, name='approve_vacation_app'),
    url(r'^pending_approvals/disapprove_vacation_app$', disapprove_vacation_app, name='disapprove_vacation_app'),
    url(r'^pending_approvals/approve_absence_app$', approve_absence_app, name='approve_absence_app'),
    url(r'^pending_approvals/disapprove_absence_app$', disapprove_absence_app, name='disapprove_absence_app'),

schedulingcalendar/views/views_export_to_csv.py
from django.template import loader
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils import timezone
from .views_basic_pages import manager_check
from ..forms import ExportToCSVForm
from ..models import Schedule, Department, Employee, BusinessData
from ..serializers import get_json_err_response
from datetime import datetime, date, time
import csv


@login_required
@user_passes_test(manager_check, login_url="/live_calendar/")  
def export_to_csv_page(request):
    """Display the csv exporting page for a managing user."""
    logged_in_user = request.user
    
    template = loader.get_template('schedulingcalendar/exportToCSV.html')
    context = {}
    export_to_csv_form = ExportToCSVForm()
    context['form'] = export_to_csv_form

    return HttpResponse(template.render(context, request))
    
    
@login_required
@user_passes_test(manager_check, login_url="/live_calendar/")  
def export_schedules_to_csv(request):
    """Generate CSV file of all schedules in date range."""
    logged_in_user = request.user
    if request.method == 'GET':
        form = ExportToCSVForm(request.GET)
        if form.is_valid():
            date_start = form.cleaned_data['month_year_start']
            date_end = form.cleaned_data['month_year_end']
            
            # Create timezone aware datetimes from date ranges
            now = timezone.now()
            dt_start = datetime.combine(date_start, now.time())
            dt_end = datetime.combine(date_end, now.time())
            
            schedules = (Schedule.objects.select_related('department', 'employee')
                                         .filter(user=logged_in_user, start_datetime__range=(dt_start, dt_end))
                                         .order_by('department', 'employee', 'start_datetime', 'end_datetime'))
            
            # Create CSV file
            business_data = BusinessData.objects.get(user=logged_in_user)
            company_name = business_data.company_name.replace(" ", "")
            start_str = date_start.strftime("%Y-%m")
            end_str = date_end.strftime("%Y-%m")
            file_name = company_name + "-" + start_str + "-to-" + end_str
            
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename='+file_name+'.csv'

            writer = csv.writer(response)
            writer.writerow(['Department', 'Employee', 'Start Time', 'End Time', 
                             'Start time was hidden?', 'End time was hidden?',
                             'Note'])
                             
            for s in schedules:
                writer.writerow([s.department, s.employee, 
                                 s.start_datetime.isoformat(), s.end_datetime.isoformat(), 
                                 s.hide_start_time, s.hide_end_time, s.schedule_note])

            return response
        else:
            msg = 'Invalid form data'
            return get_json_err_response(msg)
    else:
        msg = 'HTTP request needs to be GET. Got: ' + request.method
        return get_json_err_response(msg)

schedulingcalendar/templates/schedulingcalendar/_employeelessModal.html
<!-- Modal -->
<div id="employeelessModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <div class="text-center">
          <h4 class="modal-title">You Have Not Created Any Employees Yet</h4>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <div class="modal-body">
        <div class="legend-note">
          <span>Click the button 'Create New Employee' below to be redirected
          to the create new employee page. After you create the employee click
          edit employee to add them to any departments you would like them to
          belong to.
          </span>
        </div>
        <br>
        <div class="legend-note">
          <span><b>Note: When you load the calendar for a given department, only
          employees that are members of that department will show up.</b>
          </span>
        </div>
      </div>

      <div class="modal-footer">
        <div class="text-center">
          <a class="btn btn-primary"
             style="color:white;"
             href="{% url 'schedulingcalendar:employee_create' %}">Create New Employee</a>
          <button type="button" 
                  class="btn btn-danger"
                  data-dismiss="modal">Close Alert</button>
        </div>
      </div>
    </div>
  </div>
</div>

schedulingcalendar/templates/schedulingcalendar/absenceDelete.html
{% extends "schedulingcalendar/__baseFormCard.html" %}

{% block sub_navbar %}
  <div class="back-navbar">
      <a class="go-back-link"
         href="{% url 'schedulingcalendar:employee_info' employee.id %}">Return To {{ employee.first_name }} {{ employee.last_name }}'s Page</a>
  </div>
{% endblock sub_navbar %}  

{% block form_content %}
  <div class="text-center">
    <h4 class="card-title text-center">Are You Sure You Want To Delete This Unavailability?</h4>
    <form id="delete-absence-form"
          name= "DeleteAbsenceForm"
          action="{% url 'schedulingcalendar:absent_delete' employee.id absence.id %}"
          method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger" value="Delete Absence">
    </form>
  </div>
{% endblock form_content %}  

schedulingcalendar/templates/schedulingcalendar/absenceUpdate.html
{% extends "schedulingcalendar/__baseFormCard.html" %}
{% load static %}
{% load widget_tweaks %}

{% block sub_navbar %}
  <div class="back-navbar">
      <a class="go-back-link"
         href="{% url 'schedulingcalendar:employee_info' employee.id %}">Return To {{ employee.first_name }} {{ employee.last_name }}'s Page</a>
  </div>
{% endblock sub_navbar %}  

{% block form_content %}
  <h4 class="card-title text-center">Edit Unavailability For {{ employee.first_name }} {{ employee.last_name }}</h4>
  <form id="update-absence-form"
        name= "UpdateAbsenceForm"
        action="{% url 'schedulingcalendar:absent_update' employee.id absence.id %}"
        method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
        {{ field.errors }}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% if field.help_text %}
          <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
      </div>
    {% endfor %}
    <!-- Custom datetime pickadate elements -->
      <div id="hidden-datetime">
        <input type="text" id="hidden-start-date"/>
        <input type="text" id="hidden-start-time"/>
        <input type="text" id="hidden-end-date"/>
        <input type="text" id="hidden-end-time"/>
      </div>
      <div id="outlet"></div>
    <input type="submit" class="btn btn-primary" value="Save Changes">
  </form>
{% endblock form_content %}

{% block javascript %}
  {{ block.super }}  
  <script src="{% static 'schedulingcalendar/js/vacation.datepicker.js' %}" ></script>
{% endblock javascript %}  

schedulingcalendar/templates/schedulingcalendar/employeeUserDelete.html
{% extends "schedulingcalendar/__baseFormCard.html" %}

{% block sub_navbar %}
  <div class="back-navbar">
      <a class="go-back-link"
         href="{% url 'schedulingcalendar:employee_info' employee.id %}">Return To {{ employee.first_name }} {{ employee.last_name }}'s Page</a>
  </div>
{% endblock sub_navbar %}  

{% block form_content %}
  <div class="text-center">
    <h4 class="card-title text-center">Are You Sure You Want To Delete This Department Membership?</h4>
    <form id="delete-login-account-form"
          name= "DeleteLoginAccountForm"
          action="{% url 'schedulingcalendar:employee_user_delete' employee.id user.id %}"
          method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger" value="Delete Login Account For Employee">
    </form>
  </div>
{% endblock form_content %}

schedulingcalendar/templates/schedulingcalendar/employeeUserUpdate.html
{% extends "schedulingcalendar/__baseFormCard.html" %}
{% load widget_tweaks %}

{% block sub_navbar %}
  <div class="back-navbar">
      <a class="go-back-link"
         href="{% url 'schedulingcalendar:employee_info' employee.id %}">Return To {{ employee.first_name }} {{ employee.last_name }}'s Page</a>
  </div>
{% endblock sub_navbar %}  

{% block form_content %}
  <h4 class="card-title text-center">Edit Login Details For {{ employee.first_name }} {{ employee.last_name }}</h4>
  <form id="update-login-account-form"
        name= "UpdateLoginAccountForm"
        action="{% url 'schedulingcalendar:employee_user_update' employee.id user.id %}"
        method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
       {{ field.errors }}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% if field.help_text %}
          <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
      </div>
    {% endfor %}
    <input type="submit" class="btn btn-primary" value="Save Changes">
  </form>
{% endblock form_content %} 

schedulingcalendar/templates/schedulingcalendar/index.html
{% extends "site/__base.html" %}

{% block stylesheets %}
  {{ block.super }}
  {% load static %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
  <link rel="stylesheet" href="{% static 'schedulingcalendar/css/default.css' %}" />
  <link rel="stylesheet" href="{% static 'schedulingcalendar/css/default.time.css' %}" />
  <link rel="stylesheet" href="{% static 'schedulingcalendar/css/fullcalendar.css' %}" />
  <link rel="stylesheet" href="{% static 'schedulingcalendar/css/fullcalendar-custom.css' %}" />
  <link rel="stylesheet" href="{% static 'schedulingcalendar/css/fullcalendar.print.css' %}" media="print" />
  <link rel="stylesheet" href="{% static 'schedulingcalendar/css/fullcalendar-print-custom.css' %}" media="print" />
{% endblock stylesheets %}

{% block content %}
  <!-- Modal used for dialogs -->
  {% include "schedulingcalendar/_conflictModal.html" %}
    
  <div class="container-fluid">
    <div class="row">
      <div class="col-md">
        <!-- Calendar Toolbar -->
        <aside class="calendar-page-toolbar no-print">
          <section class="calendar-loader">
            <form id="load-calendar-form"
                  action="{% url 'schedulingcalendar:get_schedules' %}"
                  onsubmit="return(validateGetCalendarForm())"
                  method="get">
              {% csrf_token %}
              
              {% for field in calendar_form %}
                {{ field.errors }}
                {{ field.label_tag }} 
                <div class="select-cal-loader">
                  {{ field }}
                </div>
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
              {% endfor %}
              <input type="submit" class="calendar-loader-btn" id="get-calendar-button" value="Get Calendar">
            </form>
          </section>
        </aside>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <!-- Schedule Editor -->
        <aside class="schedule-editor no-print">
          <section class="schedule-adder">
            <h1>Schedule Editor</h1>
            <form id="schedule-add-form"
                  name= "addingScheduleForm"
                  action="{% url 'schedulingcalendar:add_schedule' %}"
                  onsubmit="return(validateAddScheduleForm())" 
                  method="post" 
                  align="left">
              {% csrf_token %}
              
              {{ add_sch_form.non_field_errors }}
              {{ add_sch_form.add_date.errors }}
              {{ add_sch_form.add_date }}
              
              {{ add_sch_form.department.errors }}
              {{ add_sch_form.department }}
              
              {{ add_sch_form.start_time.errors }}
              {{ add_sch_form.start_time.label_tag }}
              {{ add_sch_form.start_time }}
              
              <div class="checkbox-custom-container">
                <div class="checkbox-custom">
                  {{ add_sch_form.hide_start.errors }}
                  {{ add_sch_form.hide_start }}
                  {{ add_sch_form.hide_start.label_tag }}
                </div>
                <span class="checkbox-custom-text">Hide Start Time</span>
              </div>
              
              {{ add_sch_form.end_time.errors }}
              {{ add_sch_form.end_time.label_tag }}
              {{ add_sch_form.end_time }}
              
              <div class="checkbox-custom-container">
                <div class="checkbox-custom">
                  {{ add_sch_form.hide_end.errors }}
                  {{ add_sch_form.hide_end }}
                  {{ add_sch_form.hide_end.label_tag }}
                </div>
                <span class="checkbox-custom-text">Hide Start Time</span>
              </div>
              
              <input type="submit" value="Add Schedule">
            </form>
          </section>
                
          <section id="schedule-info">
            <h3 id="eligable-list-header">Eligable List</h3>
            <ul id="eligable-list"></ul>
          </section>
        </aside>
      </div>

      <div class="col-md-10">
        <!-- Fullcalendar -->
        <section>
          <div id="calendar"></div>
        </section>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascript %}
  {{ block.super }}     
  <script src="{% static 'schedulingcalendar/js/fullcalendar.js' %}" ></script>
  <script src="{% static 'schedulingcalendar/js/picker.js' %}" ></script>
  <script src="{% static 'schedulingcalendar/js/picker.time.js' %}" ></script>
  <script src="{% static 'schedulingcalendar/js/rescheduler.js' %}" ></script>
{% endblock javascript %}    

schedulingcalendar/templates/schedulingcalendar/monthlyRevenueDelete.html
{% extends "schedulingcalendar/__baseFormCard.html" %}

{% block sub_navbar %}
  <div class="back-navbar">
      <a class="go-back-link"
         href="{% url 'schedulingcalendar:monthly_revenue_list' %}">Return To Monthly Revenue List</a>
  </div>
{% endblock sub_navbar %}  

{% block form_content %}
  <div class="text-center">
    <h4 class="card-title text-center">Are You Sure You Want To Delete This Monthly Revenue?</h4>
    <form id="delete-monthly-revenue-form"
          name= "DeleteMonthlyRevenueForm"
          action="{% url 'schedulingcalendar:monthly_revenue_delete' monthlyrevenue.id %}"
          method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger" value="Delete Monthly Revenue">
    </form>
  </div>
{% endblock form_content %}

schedulingcalendar/templates/schedulingcalendar/repeatUnavailableCreate.html
{% extends "schedulingcalendar/__baseFormCard.html" %}
{% load static %}
{% load widget_tweaks %}

{% block sub_navbar %}
  <div class="back-navbar">
      <a class="go-back-link"
         href="{% url 'schedulingcalendar:employee_info' employee.id %}">Return To {{ employee.first_name }} {{ employee.last_name }}'s Page</a>
  </div>
{% endblock sub_navbar %}  

{% block form_content %}
  <h4 class="card-title text-center">Create Repeat Unavailability For {{ employee.first_name }} {{ employee.last_name }}</h4>
  <form id="create-repeat-unavailable-form"
        name= "CreateRepeatUnavailableForm"
        action="{% url 'schedulingcalendar:repeat_unav_create' employee.id %}"
        method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
        {{ field.errors }}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
      </div>
    {% endfor %}
    <input type="submit" class="btn btn-primary" value="Create Repeating Unavailability">
  </form>
{% endblock form_content %} 

{% block javascript %}
  {{ block.super }}  
  <script src="{% static 'schedulingcalendar/js/repeat.timepicker.js' %}" ></script>
{% endblock javascript %}  

schedulingcalendar/templates/schedulingcalendar/vacationDelete.html
{% extends "schedulingcalendar/__baseFormCard.html" %}

{% block sub_navbar %}
  <div class="back-navbar">
      <a class="go-back-link"
         href="{% url 'schedulingcalendar:employee_info' employee.id %}">Return To {{ employee.first_name }} {{ employee.last_name }}'s Page</a>
  </div>
{% endblock sub_navbar %}  

{% block form_content %}
  <div class="text-center">
    <h4 class="card-title text-center">Are You Sure You Want To Delete This Vacation?</h4>
    <form id="delete-vacation-form"
          name= "DeleteVacationForm"
          action="{% url 'schedulingcalendar:vacation_delete' employee.id vacation.id %}"
          method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger" value="Delete Vacation">
    </form>
  </div>
{% endblock form_content %}  